[tool.poetry]
name = "py33"
version = "0.1.0"
description = ""
authors = ["Ulan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
